"""Dependency graph between template entities (agents/hooks/loops/skills),
extracted from actual file content.

This is a maintainer tool for reasoning about this repo's own template
catalog - "what breaks if I touch category X" - not a CLI-selection
feature. It does not affect `generate`'s behavior; see cli.py's `graph`
command for the only consumer.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from awesome_templates.catalog import KIND_ALIAS, KINDS, SKIP_NAMES, Catalog, discover
from awesome_templates.workspace import Workspace

KIND_SINGULAR = {plural: singular for singular, plural in KIND_ALIAS.items()}

BEGIN_MARKER_MD = "<!-- BEGIN AUTOGENERATED: dependencies -->"
END_MARKER_MD = "<!-- END AUTOGENERATED: dependencies -->"
BEGIN_MARKER_PY = "# BEGIN AUTOGENERATED: dependencies"
END_MARKER_PY = "# END AUTOGENERATED: dependencies"


@dataclass(frozen=True, order=True)
class EntityRef:
    category: str
    kind: str
    name: str

    @property
    def is_doc(self) -> bool:
        return self.kind == "doc"


@dataclass(frozen=True)
class Edge:
    source: EntityRef
    target: EntityRef

    @property
    def same_category(self) -> bool:
        return self.source.category == self.target.category


@dataclass
class DependencyGraph:
    nodes: list[EntityRef]
    edges: list[Edge]
    missing: set[EntityRef] = field(default_factory=set)


def _entity_text(kind: str, path: Path) -> str:
    if kind == "skills":
        parts = []
        for f in sorted(path.rglob("*")):
            if not f.is_file() or f.name in SKIP_NAMES or f.name.endswith("MIGRATION_REPORT.md"):
                continue
            try:
                parts.append(f.read_text(encoding="utf-8"))
            except UnicodeDecodeError:
                continue
        return "\n".join(parts)
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return ""


def build_dependency_graph(
    workspace: Workspace,
    catalog: Catalog | None = None,
    extra_scan_path: Path | None = None,
) -> DependencyGraph:
    """Scan every entity's own content for whole-word mentions of every other
    entity's name. A match on the source entity's own name is never an edge
    (self-mentions are discarded outright, not just self-loops). A match on
    a name shared by entities in more than one category (e.g. the deliberate
    _common hook duplication) resolves to same-category entities first, and
    only fans out to other categories when the source's own category has no
    entity of that name (a real, useful signal - see e.g. java/agents/
    java-expert.md referencing security-auditor, which only exists under
    python/)."""
    catalog = catalog or discover(workspace)

    nodes: list[EntityRef] = []
    by_name: dict[str, list[EntityRef]] = {}
    texts: dict[EntityRef, str] = {}

    for cat, kinds in catalog.entries.items():
        for kind in KINDS:
            for name, path in kinds[kind].items():
                ref = EntityRef(category=cat, kind=kind, name=name)
                nodes.append(ref)
                by_name.setdefault(name, []).append(ref)
                texts[ref] = _entity_text(kind, path)

    # If an extra scan path (like docs/) is provided, we scan its files too
    if extra_scan_path and extra_scan_path.is_dir():
        for f in extra_scan_path.rglob("*"):
            if f.is_file() and f.suffix in (".md", ".py") and f.name not in SKIP_NAMES:
                try:
                    rel_path = f.relative_to(extra_scan_path)
                    ref = EntityRef(category="docs", kind="doc", name=str(rel_path))
                    nodes.append(ref)
                    texts[ref] = f.read_text(encoding="utf-8")
                except (UnicodeDecodeError, ValueError):
                    continue

    nodes.sort()

    if not nodes:
        return DependencyGraph(nodes=nodes, edges=[])

    pattern_names = sorted(by_name, key=len, reverse=True)
    pattern = (
        re.compile(
            r"(?<![\w-])(" + "|".join(re.escape(n) for n in pattern_names) + r")(?![\w-])"
        )
        if pattern_names
        else None
    )

    doc_pattern = re.compile(r"@docs/([a-zA-Z0-9_\-/]+\.md)")
    source_pattern = re.compile(r"(?<![\w\-/])(\.?[a-zA-Z0-9_\-/]+\.py)(?![\w\.])")

    edges: list[Edge] = []
    seen: set[tuple[EntityRef, EntityRef]] = set()

    # To track discovered documentation and source files (those that are targets but not in nodes)
    extra_nodes: set[EntityRef] = set()

    for ref in nodes:
        # Match standard entities
        if pattern:
            matched_names = {m.group(1) for m in pattern.finditer(texts[ref])}
            matched_names.discard(ref.name)
            for name in matched_names:
                targets = by_name[name]
                same_category = [t for t in targets if t.category == ref.category]
                for target in same_category or targets:
                    key = (ref, target)
                    if key not in seen:
                        seen.add(key)
                        edges.append(Edge(source=ref, target=target))

        # Match @docs/ references
        matched_docs = {m.group(1) for m in doc_pattern.finditer(texts[ref])}
        for doc_path in matched_docs:
            target = EntityRef(category="docs", kind="doc", name=doc_path)
            extra_nodes.add(target)
            key = (ref, target)
            if key not in seen:
                seen.add(key)
                edges.append(Edge(source=ref, target=target))

        # Match .py source references
        matched_sources = {m.group(1) for m in source_pattern.finditer(texts[ref])}
        for src_path in matched_sources:
            # We treat these as a special "src" kind
            target = EntityRef(category="src", kind="file", name=src_path)
            extra_nodes.add(target)
            key = (ref, target)
            if key not in seen:
                seen.add(key)
                edges.append(Edge(source=ref, target=target))

    # Add discovered extra nodes to nodes
    missing: set[EntityRef] = set()
    for extra_ref in sorted(extra_nodes):
        if extra_ref not in nodes:
            nodes.append(extra_ref)
            # Check existence for docs and files
            if extra_ref.kind == "doc":
                if not (workspace.root / "docs" / extra_ref.name).exists():
                    missing.add(extra_ref)
            elif extra_ref.kind == "file":
                if not (workspace.root / extra_ref.name).exists():
                    missing.add(extra_ref)

    nodes.sort()
    return DependencyGraph(nodes=nodes, edges=edges, missing=missing)


def _sanitize(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _node_id(ref: EntityRef) -> str:
    return f"{ref.kind}__{ref.category}__{_sanitize(ref.name)}"


def _node_label(ref: EntityRef) -> str:
    if ref.kind == "doc":
        return f"doc:{ref.name}"
    if ref.kind == "file":
        return f"src:{ref.name}"
    label = f"{KIND_SINGULAR.get(ref.kind, ref.kind)}:{ref.name}"
    if ref.category != ".":
        label = f"{ref.category}/{label}"
    return label


def render_mermaid(graph: DependencyGraph) -> str:
    """graph LR, grouped into one subgraph per category (not per kind - both
    the deliberate cross-category duplicates and the dangling cross-category
    references this graph exists to surface are category-shaped). Edges
    within a category render solid; edges crossing categories render dashed,
    as a visual flag for the "what breaks" question."""
    by_category: dict[str, list[EntityRef]] = {}
    for ref in graph.nodes:
        by_category.setdefault(ref.category, []).append(ref)

    lines = ["graph LR"]
    for cat in sorted(by_category):
        use_subgraph = cat != "."
        if use_subgraph:
            lines.append(f"  subgraph {cat}")
        for ref in by_category[cat]:
            indent = "    " if use_subgraph else "  "
            lines.append(f'{indent}{_node_id(ref)}["{_node_label(ref)}"]')
        if use_subgraph:
            lines.append("  end")

    for edge in graph.edges:
        arrow = "-->" if edge.same_category else "-.->"
        lines.append(f"  {_node_id(edge.source)} {arrow} {_node_id(edge.target)}")

    return "\n".join(lines) + "\n"


def render_doc(graph: DependencyGraph) -> str:
    cross_category = sorted(
        (e for e in graph.edges if not e.same_category),
        key=lambda e: (e.source.category, e.source.kind, e.source.name, e.target.category, e.target.name),
    )
    referenced = {e.target for e in graph.edges}
    orphans = sorted(ref for ref in graph.nodes if ref not in referenced)

    lines = [
        "# Template Catalog Dependency Graph",
        "",
        "Auto-generated by `awesome_templates graph` from the actual content of "
        "`templates/**` - do not hand-edit; regenerate instead.",
        "",
        "```mermaid",
        render_mermaid(graph).rstrip("\n"),
        "```",
        "",
        "## Cross-category edges",
        "",
        "Entities that reference something outside their own category - worth a "
        "second look, since it means selecting the source's category without the "
        "target's category ships a dangling reference.",
        "",
    ]
    if cross_category:
        for e in cross_category:
            source_label = (
                f"{e.source.kind}:{e.source.name}"
                if e.source.category == "."
                else f"{e.source.kind}:{e.source.category}/{e.source.name}"
            )
            target_label = (
                f"{e.target.kind}:{e.target.name}"
                if e.target.category == "."
                else f"{e.target.kind}:{e.target.category}/{e.target.name}"
            )
            lines.append(f"- `{source_label}` -> `{target_label}`")
    else:
        lines.append("(none found)")

    lines += [
        "",
        "## Missing references",
        "",
        "These files are referenced in the catalog but do not exist on disk.",
        "",
    ]
    if graph.missing:
        for ref in sorted(graph.missing):
            label = "@docs/" + ref.name if ref.kind == "doc" else ref.name
            lines.append(f"- `{label}`")
    else:
        lines.append("(none detected)")

    lines += [
        "",
        "## Nodes with no detected references",
        "",
        "Nothing in the scanned entity content points at these - either a true "
        "leaf (fine) or only referenced from settings.json / docs, which this "
        "scan does not read.",
        "",
    ]
    if orphans:
        for ref in orphans:
            label = (
                f"{ref.kind}:{ref.name}"
                if ref.category == "."
                else f"{ref.kind}:{ref.category}/{ref.name}"
            )
            lines.append(f"- `{label}`")
    else:
        lines.append("(none - every node is referenced by at least one other entity)")

    return "\n".join(lines) + "\n"


def _dependency_token(source: EntityRef, target: EntityRef) -> str:
    if target.kind == "doc":
        return f"doc:{target.name}"
    if target.kind == "file":
        return f"src:{target.name}"
    singular = KIND_SINGULAR.get(target.kind, target.kind)
    if target.category == source.category or target.category == ".":
        return f"{singular}:{target.name}"
    return f"{singular}:{target.category}/{target.name}"


def _outgoing_targets(source: EntityRef, graph: DependencyGraph) -> list[EntityRef]:
    targets = [e.target for e in graph.edges if e.source == source]
    return sorted(targets, key=lambda t: (t.kind, t.category, t.name))


def render_dependency_block_markdown(source: EntityRef, graph: DependencyGraph) -> str:
    targets = _outgoing_targets(source, graph)
    lines = [BEGIN_MARKER_MD, "## Dependencies", ""]
    if targets:
        lines += [f"- `{_dependency_token(source, t)}`" for t in targets]
    else:
        lines.append("(none detected)")
    lines += ["", END_MARKER_MD]
    return "\n".join(lines)


def render_dependency_block_python(source: EntityRef, graph: DependencyGraph) -> str:
    targets = _outgoing_targets(source, graph)
    lines = [BEGIN_MARKER_PY, "# Dependencies:"]
    if targets:
        lines += [f"# - {_dependency_token(source, t)}" for t in targets]
    else:
        lines.append("# (none detected)")
    lines.append(END_MARKER_PY)
    return "\n".join(lines)


def markdown_frontmatter_end(text: str) -> int | None:
    """Position right after a leading `---`-fenced frontmatter block, or None
    if the text doesn't start with one. Anchored at file-start with a
    newline-bounded closing fence so it isn't fooled by a `---` horizontal
    rule or a `|---|---|` table-divider row later in the body."""
    m = re.match(r"^---\r?\n.*?\r?\n---[ \t]*\r?\n", text, re.DOTALL)
    return m.end() if m else None


def python_insertion_point(text: str) -> int:
    """Position after a leading shebang line and/or module docstring, or 0
    if the file has neither."""
    pos = 0
    shebang = re.match(r"#![^\n]*\n", text)
    if shebang:
        pos = shebang.end()
    docstring = re.match(r"(\"\"\"|''')(?:.*?)\1[ \t]*\r?\n?", text[pos:], re.DOTALL)
    if docstring:
        pos += docstring.end()
    return pos


def remove_marked_block(text: str, begin_marker: str, end_marker: str) -> tuple[str, bool]:
    """Remove a marker-delimited block and its surrounding padding."""
    region_re = re.compile(
        r"\n*" + re.escape(begin_marker) + r".*?" + re.escape(end_marker) + r"\n*", re.DOTALL
    )
    m = region_re.search(text)
    if not m:
        return text, False

    head, tail = text[: m.start()], text[m.end() :]
    head = head.rstrip("\n")
    tail = tail.lstrip("\n")

    if head and tail:
        new_text = head + "\n\n" + tail
    else:
        new_text = head + tail

    # Ensure it ends with exactly one newline if not empty
    if new_text and not new_text.endswith("\n"):
        new_text += "\n"

    return new_text, True


def upsert_marked_block(
    text: str, canonical_block: str, begin_marker: str, end_marker: str, insertion_point: int
) -> str:
    """Idempotently insert or replace a marker-delimited block. Matches the
    marked region plus its surrounding blank-line padding in one pass, so
    re-running with the same canonical_block reproduces byte-identical text
    (padding is normalized, not accumulated) - see dependencies.py's plan for
    the stability argument."""
    region_re = re.compile(
        r"\n*" + re.escape(begin_marker) + r".*?" + re.escape(end_marker) + r"\n*", re.DOTALL
    )
    m = region_re.search(text)
    if m:
        head, tail = text[: m.start()], text[m.end() :]
    else:
        head, tail = text[:insertion_point], text[insertion_point:]
    head = head.rstrip("\n")
    tail = tail.lstrip("\n")

    pieces = []
    if head:
        pieces.append(head + "\n\n")
    pieces.append(canonical_block)
    pieces.append("\n" + tail if tail else "\n")
    return "".join(pieces)


def write_inline_dependencies(
    workspace: Workspace,
    catalog: Catalog | None = None,
    log_verbosity: int = 0,
    extra_scan_path: Path | None = None,
    force: bool = False,
    remove: bool = False,
) -> int:
    """Upsert or remove a per-entity 'Dependencies' block into every
    templates/** entity file.

    MUTATES templates/** in place.
    module (and every other command in this CLI), which only ever writes to
    a destination outside templates/. Callers must treat this as a manual,
    reviewed maintainer action (review `git diff` before committing), never
    something invoked implicitly from `generate` or any other command.

    Returns the number of files actually changed; re-running with an
    unchanged catalog changes zero files (see upsert_marked_block)."""
    catalog = catalog or discover(workspace)
    graph = build_dependency_graph(workspace, catalog, extra_scan_path=extra_scan_path)

    updated = 0
    # Collect all paths to update.
    # Map from Path to its EntityRef
    to_update: dict[Path, EntityRef] = {}

    for cat, kinds in catalog.entries.items():
        for kind in KINDS:
            for name, path in kinds[kind].items():
                ref = EntityRef(category=cat, kind=kind, name=name)
                target_path = (path / "SKILL.md") if kind == "skills" else path
                if target_path.is_file():
                    to_update[target_path] = ref

    if extra_scan_path and extra_scan_path.is_dir():
        for f in extra_scan_path.rglob("*"):
            if f.is_file() and f.suffix in (".md", ".py") and f.name not in SKIP_NAMES:
                try:
                    rel_path = f.relative_to(extra_scan_path)
                    ref = EntityRef(category="docs", kind="doc", name=str(rel_path))
                    to_update[f] = ref
                except ValueError:
                    continue

    if not force and not remove:
        for target_path in to_update:
            try:
                original = target_path.read_text(encoding="utf-8")
                marker = BEGIN_MARKER_PY if target_path.suffix == ".py" else BEGIN_MARKER_MD
                if marker in original:
                    raise RuntimeError(
                        f"Dependencies already generated in {target_path}. Use --force to regenerate."
                    )
            except UnicodeDecodeError:
                continue

    for target_path, ref in to_update.items():
        try:
            original = target_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        begin_marker, end_marker = (
            (BEGIN_MARKER_PY, END_MARKER_PY)
            if target_path.suffix == ".py"
            else (BEGIN_MARKER_MD, END_MARKER_MD)
        )

        if remove:
            new_text, was_removed = remove_marked_block(original, begin_marker, end_marker)
            if log_verbosity >= 2:
                try:
                    rel_path = target_path.relative_to(workspace.root)
                except ValueError:
                    rel_path = target_path
                status = "removed block" if was_removed else "(no block found)"
                print(f"  {rel_path}: {status}")

            if was_removed:
                target_path.write_text(new_text, encoding="utf-8")
                updated += 1
            continue

        if log_verbosity >= 2:
            targets = _outgoing_targets(ref, graph)
            n_entities = len([t for t in targets if t.kind not in ("doc", "file")])
            n_docs = len([t for t in targets if t.kind == "doc"])
            n_code = len([t for t in targets if t.kind == "file"])
            try:
                rel_path = target_path.relative_to(workspace.root)
            except ValueError:
                rel_path = target_path
            print(f"  {rel_path}: {n_entities} entities, {n_code} code, {n_docs} docs")
            for t in targets:
                if t in graph.missing:
                    if t.kind == "doc":
                        print(f"    [!] missing doc: @docs/{t.name}")
                    elif t.kind == "file":
                        print(f"    [!] missing code: {t.name}")

        try:
            original = target_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        if target_path.suffix == ".py":
            block = render_dependency_block_python(ref, graph)
            insertion_point = python_insertion_point(original)
            # markers already set above
        else:
            block = render_dependency_block_markdown(ref, graph)
            fm_end = markdown_frontmatter_end(original)
            insertion_point = fm_end if fm_end is not None else 0
            # markers already set above

        new_text = upsert_marked_block(
            original, block, begin_marker, end_marker, insertion_point
        )
        if new_text != original:
            target_path.write_text(new_text, encoding="utf-8")
            updated += 1
    return updated


def to_json(graph: DependencyGraph) -> dict:
    def _ref(ref: EntityRef) -> dict:
        return {"category": ref.category, "kind": ref.kind, "name": ref.name}

    return {
        "nodes": [_ref(ref) for ref in graph.nodes],
        "edges": [
            {
                "source": _ref(e.source),
                "target": _ref(e.target),
                "same_category": e.same_category,
            }
            for e in graph.edges
        ],
        "missing": [_ref(ref) for ref in sorted(graph.missing)],
    }
